{
 "title": "Paimon Bank Request",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (path, method, status) (rate(paimon_bank_requests_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (path, method, status) (rate(paimon_bank_requests_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (path, method, status) (rate(paimon_bank_requests_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"local-metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(paimon_bank_requests_bucket{status=\"500\"}[$__rate_interval])) by (method, path, status)",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(paimon_bank_requests_count[$__rate_interval])) by (path, method, status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}