{
 "title": "Paimon Bank Request",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Observability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"local-metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(paimon_bank_requests_bucket{status=\"500\"}[$__rate_interval])) by (path, method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(paimon_bank_requests_count[$__rate_interval])) by (path, method, status)",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (path, method, status) (rate(paimon_bank_requests_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (path, method, status) (rate(paimon_bank_requests_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (path, method, status) (rate(paimon_bank_requests_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "paimon_bank_requests_count{path=\"/v1/user/login\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "paimon_bank_requests_count{path=\"/v1/balance\",  method=\"POST\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "paimon_bank_requests_count{path=\"/v1/user/register\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "paimon_bank_requests_count{method=\"GET\", path=\"/v1/balance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "paimon_bank_requests_count{path=\"/v1/balance/history\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "paimon_bank_requests_count{path=\"/v1/transaction\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}